### ISSUE TITLE
Request to update the WebXR example with latest polyfill for ML Helio.

### ISSUE THREAD

**Issue by yhuangbrowser** [immersive-web/immersiveweb.dev#14]
The [demo of VR and AR](https://toji.github.io/webxr-particles/) is using outdated HelioWebXRPolyfill.js file, which causes issues when view this example in XR mode on ML Helio.
Is there anyway to contact the author of this example to update the website with the latest Helio WebXR polyfill, which is already in the latest three.js repo: https://github.com/mrdoob/three.js/blob/dev/examples/js/vr/HelioWebXRPolyfill.js so that it works on Helio as well?

**Comment by AdaRoseCannon** [comment]
Probably it would be best to submit a PR to three.js itself to get that updated.

**Comment by yhuangbrowser** [comment]
Is this example from three.js repo? three.js repo already has the latest HelioWebXRPolyfill.js, but the example includes an old copy of it.

**Comment by AdaRoseCannon** [comment]
Ah this is from https://toji.github.io/webxr-particles/

It will need to be updated here: https://github.com/toji/webxr-particles

**Comment by yhuangbrowser** [comment]
I see. I'll update it to that repo directly. Thanks!
