### ISSUE TITLE
Update support table to remove Firefox Reality and Helio Browser?

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/immersiveweb.dev#39]
From what I can tell neither of these browsers are continuing to update.

Should they be removed from the support table?

**Comment by AdaRoseCannon** [comment]
@Manishearth as someone who used to work on Firefox Reality, what do you think?

**Comment by Manishearth** [comment]
I worked on the Hololens one, which is an entirely different piece of software based on Servo. I don't precisely know what the situation is with Firefox Reality, I think there are still some people working on it? But I'm not sure.

**Comment by AdaRoseCannon** [comment]
Alright i'll close this 👍
