### ISSUE TITLE
Add lighting Estimation to the Support Table

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/immersiveweb.dev#40]
Lighting Estimation has some support now it should be added to the table.

@klausw would you be able to make a PR to add this?

**Comment by klausw** [comment]
@toji , do you want to take this one? I haven't been following it closely, I got the impression there's still some open issues about the API shape.

**Comment by toji** [comment]
Sure, will do!

**Comment by toji** [comment]
Fixed by 0b85c17f5f2c6c27bc3e5756cc48712db1f0685c
