### ISSUE TITLE
Getting started for WebXR in Unity

### ISSUE THREAD

**Issue by De-Panther** [immersive-web/immersiveweb.dev#43]
I would like to help with a getting started in Unity.

Currently there are 3 main exporters that I know of.
[Mozilla's WebXR Exporter](https://github.com/MozillaReality/unity-webxr-export)
[WebXR Export](https://github.com/De-Panther/unity-webxr-export)
[SimpleWebXR](https://github.com/Rufus31415/Simple-WebXR-Unity)

I can help with the exporter that I'm maintaining.

As it's a visual editor, the minimum setup is mostly visual, and more complex stuff can/need to use code.

I'm not sure what the user would expect to see in a short getting started.
Do you think that importing existing sample and build is enough?

Thanks

**Comment by De-Panther** [comment]
Something like:

Create new Unity Project (2019.4.7f1 and Up in the 2019.4.x cycle).
Switch platform to WebGL.

Import WebXR Export and WebXR Interactions packages from OpenUPM
https://openupm.com/packages/com.de-panther.webxr/
https://openupm.com/packages/com.de-panther.webxr-interactions/

Once pacakges are imported, Go to Window > WebXR > Copy WebGLTemplates
![image](https://user-images.githubusercontent.com/4749703/99601751-b5046080-2a08-11eb-893a-6632db783d21.png)

After WebGLTemplates are in the Assets folder, Open the XR Plug-in Management in the Project Settings window and select the "WebXR Export" plug-in provider.
![image](https://user-images.githubusercontent.com/4749703/99601770-c3527c80-2a08-11eb-81e8-4b5baa9976c3.png)

Now you can import the "Sample Scene" from Package Manager > WebXR Interactions > Import into Project.
![image](https://user-images.githubusercontent.com/4749703/99601801-d2392f00-2a08-11eb-8eac-358e3f7a0e7b.png)

In Project Settings > Player > Resolution and Presentation, select WebXR as the WebGL Template.
![image](https://user-images.githubusercontent.com/4749703/99601825-df561e00-2a08-11eb-913d-660e00e4e363.png)

Now you can build the project.
![image](https://user-images.githubusercontent.com/4749703/99601841-ed0ba380-2a08-11eb-9570-11833fc05721.png)

Make sure to build it from Build Settings > Build.
Unity's "Build And Run" server use HTTP.
Run the build on your own HTTPS server.

![image](https://user-images.githubusercontent.com/4749703/99601859-f6950b80-2a08-11eb-818d-9c173006fca0.png)
That's it

**Comment by AdaRoseCannon** [comment]
This looks really great! Could you make a PR?

**Comment by De-Panther** [comment]
Sure! done.

**Comment by AdaRoseCannon** [comment]
Fixed by #46
