### ISSUE TITLE
Add Layers Polyfill to support table

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/immersiveweb.dev#57]
It can probably go in the polyfill column linking directly.

@cabanier what do you think?

**Comment by cabanier** [comment]
Yes, it can go there.
Do you want me to add it?

**Comment by cabanier** [comment]
@AdaRoseCannon  I accidentally committed directly to the repo :-\

**Comment by AdaRoseCannon** [comment]
That's fine lol, I accidentally did too the other day don't worry about it.
Thanks for making the change!
