### ISSUE TITLE
Update Hand Tracking support for Oculus in the support table

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/immersiveweb.dev#58]
It doesn't need a date or anything just a mention of what version it was enabled by default.

**Comment by cabanier** [comment]
It was in 15.1
I will make a PR later

**Comment by AdaRoseCannon** [comment]
Thats totally fine! Thanks for updating the table!

**Comment by himorin** [comment]
Are we better to have (well configured?) branch protection rules over immersive-web repos, @AdaRoseCannon ?
(AFAIK, we have nothing over all repos, now - or say, rules with blank setting...)

**Comment by AdaRoseCannon** [comment]
That's not a bad idea, this repo is fine as it's not a high priority one. Perhaps it's best to ask the editors before making changes though as they make the most changes.

**Comment by cabanier** [comment]
I agree that it would be great if we could disallow direct commits

**Comment by himorin** [comment]
added to administrivia, not adding agenda, do we want to discuss offline or during call?
