### ISSUE TITLE
Hello webpage doesn't work!

### ISSUE THREAD

**Issue by Johnhamminga** [immersive-web/immersiveweb.dev#70]
The hello webpage in Firefox doesn't work. The other examples do. For instance the dinosaur plays well. The browser runs on an ipad pro but the problem is persistent in the Oculus quest.

https://mixedreality.mozilla.org/hello-webxr/

**Comment by AdaRoseCannon** [comment]
Thanks for the tip I will replace this.

**Comment by msub2** [comment]
I have a mirror of the hello webxr page up at https://msub2.github.io/hello-webxr/

**Comment by AdaRoseCannon** [comment]
Shoot I had just removed it since it was broken i'll readd it using the mirror
