### ISSUE TITLE
How to local dev

### ISSUE THREAD

**Issue by marwie** [immersive-web/immersiveweb.dev#84]
Hello

What is being used for previewing the local website? 
I've just used the vscode local server but it doesnt translate/process the markdown and mustache(?) syntax.

![image](https://github.com/immersive-web/immersiveweb.dev/assets/5083203/7c5cf8bb-8610-4fd7-acf8-b25fc3ecdeaa)

**Comment by AdaRoseCannon** [comment]
it's Jekyll

**Comment by nyan-left** [comment]
I propose re-opening this issue and closing once a `CONTRIBUTING.MD` has been added.
