### ISSUE TITLE
Re-adding Servo?

### ISSUE THREAD

**Issue by msub2** [immersive-web/immersiveweb.dev#93]
I see that Servo was removed from the table back in 2021 as there was no longer any active work on it wrt Hololens. Today, however, Servo's WebXR implementation is functional on Windows (I submitted a couple patches for it last year) and there's currently work being done to add Linux support as well. Maybe it's worth adding back?

**Comment by AdaRoseCannon** [comment]
I think that makes sense, would you be able to add it to the table with the current details?

**Comment by msub2** [comment]
Sure! Will throw a PR over later today.
