### ISSUE TITLE
Support Table: Apple Vision Pro?

### ISSUE THREAD

**Issue by apowers313** [immersive-web/immersiveweb.dev#97]
Would it be worth adding Apple Vision Pro to the [Support Table](https://immersiveweb.dev/?ref=blog.mozvr.com#supporttable) on the Immersive Web home page?

Also, how does this table denote fractional support of specs? (e.g. Vision Pro currently supports "immersive-vr" but not "immersive-ar")

**Comment by AdaRoseCannon** [comment]
It is there already under "Safari on visionOS" and it already shows that it does not support "WebXR AR Module"

**Comment by apowers313** [comment]
Apologies, I don't know how I missed that column. Thanks for the quick reply!
